<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('Check micro donations for group admin');
$I->amOnPage('/');
$I->see('Login','.button');
$I->click("//a[@class='button' and text()='Login']");
$I->seeCurrentUrlEquals('/wp/wp-login.php');
$I->fillField('log','elen');
$I->fillField('pwd','funkadelicbro87');
$I->click('Log In');
$I->seeCurrentUrlEquals('/browse/elen/');
$I->click("//a[@id='user-groups']");
$I->seeCurrentUrlEquals('/browse/elen/groups/');
$I->seeElement('#groups-my-groups');
$I->click('Sex Lovers United');
$I->seeCurrentUrlEquals('/groups/sex-lovers-united/');
$I->seeElement('#members');
$I->dontSee('micro-Donate');
$I->dontSeeElement('#admin');
$I->moveMouseOver("//a[@title='My Account']");
$I->see('Log Out','.ab-item');
$I->click("//a[@class='ab-item' and text()='Log Out']");
$I->seeCurrentUrlEquals('/groups/sex-lovers-united/?loggedout=true');
$I->see('Register','li');
$I->see('Login','.button');